### PR TITLE
[on hold] Include omniscidb 5.6 on github CI

### PR DESCRIPTION
**Pull request by guilhermeleobas**
On hold until https://github.com/conda-forge/omniscidb-feedstock/pull/40 gets merged

### CODE REVIEW

**Comment by pearu** [comment]
omniscidb 5.6 is actually provided by https://github.com/conda-forge/omniscidb-feedstock/pull/39

**Comment by guilhermeleobas** [comment]
Did omniscidb went from v5.5.2 straight to 5.7-dev on conda-forge ([ref](https://anaconda.org/conda-forge/omniscidb/files))?

**Comment by pearu** [comment]
> Did omniscidb went from v5.5.2 straight to 5.7-dev on conda-forge ([ref](https://anaconda.org/conda-forge/omniscidb/files))?

yes. In fact, there is now 5.6.1 that we might want to conda packages at some point. Such a mess...

**Comment by guilhermeleobas** [comment]
😅

**Pull request closed without merging**
