### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by guilhermeleobas**

### CODE REVIEW

**Comment by tupui** [comment]
For the documentation of dunder methods, you can try this https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html?highlight=special-members#directive-option-automodule-special-members

**Comment by guilhermeleobas** [comment]
Is there a way to show dunder methods only for a specific class?

**Comment by tupui** [comment]
> Is there a way to show dunder methods only for a specific class?

Yes, instead you need to add the directive just for the class. See https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html?highlight=special-members#directive-option-automodule-special-members

**Review by pearu — APPROVED** [review]
LGTM!

**Pull request merged**
